version: '3.6'
services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./back/rails_project/db/mysql_data:/var/lib/mysql
  back:
    container_name: back
    build: ./back
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./back/rails_project:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    container_name: front
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - ./front/vue_project:/app:cached
    stdin_open: true
    tty: true
volumes:
  mysql_data:
  bundle: